name: README Dynamic Create

on:
  push:
    branches:
      - main
    paths:
      - README
      - tables/*.md
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_templates:
    name: "Update README"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create new branch
        run: |
          git checkout -b auto-update

      - name: Generate README.md
        run: |
          python replace_tag.py
          git status  # Debug: verifica alterações
          git diff    # Debug: mostra diferenças

      - name: Commit changes
        run: |
          sudo chmod -R ugo+rwX .
          git config --global user.email "github_actions@email.com"
          git config --global user.name "github_actions"
          git add .
          git commit -m "README Create Automation" || echo "Sem alterações para commit"

      - name: Push changes to new branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update

      - name: Check GH Version
        run: gh --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: pr
        run: |
          PR_URL=$(gh pr create \
            --title "README Update ${GITHUB_RUN_ID}" \
            --body "Auto-generated by GitHub Actions" \
            --base main \
            --head auto-update)

          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT

          # Extrai o número do PR da URL
          PR_NUMBER=$(basename $PR_URL)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge
        run: |
          gh pr merge ${{ steps.pr.outputs.PR_NUMBER }} \
            --enable-auto \
            --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: |
          gh pr merge ${{ steps.pr.outputs.PR_NUMBER }} \
            --admin \
            --squash \
            --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Force Cleanup (Fallback)
        if: always()
        run: |
          gh api -X DELETE "/repos/${{ github.repository }}/git/refs/heads/auto-update" \
            || echo "Branch já deletada"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
