name: README Dynamic Update

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
      - uses: actions/setup-python@v2
        run: |
          python -m pip install --upgrade pip

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://stackoverflow.com/questions/60868897/git-log-dates-incorrect-in-a-github-action
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Update README.md
        run: |
          python replace_tag.py

      - name: Commit files
        run: |
          sudo chmod -R ugo+rwX .
          git config --global user.email github_actions@email.com
          git config --global user.name github_actions
          git add .
          git commit -m "README update Automation" -a

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
