name: README Dynamic Create

on:
  push:
    paths:
      - README
      - tables/*.md
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_templates:
    name: "Update README"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create new branch
        run: |
          git checkout -b auto-update-readme-${GITHUB_RUN_ID}

      - name: Generate README.md
        run: |
          python replace_tag.py
          git status  # Debug: verifica alterações
          git diff    # Debug: mostra diferenças

      - name: Commit changes
        run: |
          sudo chmod -R ugo+rwX .
          git config --global user.email "github_actions@email.com"
          git config --global user.name "github_actions"
          git add .
          git commit -m "README Create Automation" || echo "Sem alterações para commit"

      - name: Push changes to new branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-readme-${GITHUB_RUN_ID}

      - name: Create Pull Request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: auto-update-readme-${GITHUB_RUN_ID}
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automatic README Update"
          pr_body: "Auto-generated PR from GitHub Actions"
          pr_close_comment: "This branch will be automatically deleted"
          auto_merge: true
          merge_method: merge

      - name: Delete branch if PR merged
        if: steps.pr.outputs.result == 'success'
        run: |
          git push origin --delete auto-update-readme-${GITHUB_RUN_ID} || echo "Branch already deleted"
